disabled_rules:
- trailing_whitespace
- colon
excluded:
- Pods
line_length:
    warning: 300
    error: 400
    ignores_function_declarations: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
force_cast:
    severity: errorg #explicitly
force_try:
    severity: error  #explicitly
reporter: "xcode"

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- KeychainWrapper/InternetProtocol.swift

# rules that have both warning and error levels, can set just the warning level
# implicitly

# additionally they can set excluded names
identifier_name:
    min_length: # only min_length
        error: 2 # only error
    excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
